version: '3.8'

services:
  rust:
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    volumes:
      - db_postgres_data:/var/lib/postgresql/data
    env_file:
      - env/.env
    ports:
      - 5432:5432
  python:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 80:80

volumes:
  db_postgres_data: